#!/usr/bin/env bash

# Go into the directory containing the autograder source code
cd /autograder/source

# Remove the `src` directory as we are going to copy the student
# submission's `src` directory into our autograder directory.

# Save the autograder tests
mv src/test test

# Delete the solution directory
rm -rf src

# Search for the student's `src` directory in the submission folder.
if cp -r `find /autograder/submission -maxdepth 2 -name 'src'` .; then
    echo "Found src dir in submission"
else
    echo "Couldn't find src directory in submission" | python3 scripts/build_output.py > /autograder/results/results.json
    exit
fi

# Remove student's tests
rm -rf src/test

# Move the autograder tests into students src/test directory.
mv test src/

# Build the student submission.
if ant -l /autograder/results/build.log build; then
    echo "Build succeeded"
    cat /autograder/results/build.log
else
    echo "Build failed"
    cat /autograder/results/build.log | python3 scripts/build_output.py > /autograder/results/results.json
    exit
fi

# Run the autograder and generate the results.
echo "Run grader"
java -cp "bin/:lib/*" test.RunTests > /autograder/results/results.json

# print full results for instructor to see (can this be easier to read?)
echo "Full results:"
cat /autograder/results/results.json | python3 scripts/pretty_json.py
